name: homepage4
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: ABotelho23 <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  sass_builder: ^2.0.0
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0

dev_dependencies:
  angular_test: ^2.0.0
  #build_runner: ^0.10.0
  build_test: ^0.10.2
  #build_web_compilers: ^0.4.0
  test: ^1.0.0
  #sass_builder: ^2.0.0 # update for the latest version
